create table edm.city (
  id                  serial primary key,
  name                text,
  description         text,
  photo               text,
  region              text references edm.region(name) on delete cascade,
  country             text references edm.country(code) on delete cascade,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

GRANT ALL ON TABLE edm.city TO :DATABASE_VISITOR;
CREATE POLICY select_city ON edm.city for SELECT USING (true);
CREATE POLICY insert_city ON edm.city for INSERT WITH CHECK (true);

CREATE INDEX idx_city_region ON edm.city (region);
CREATE INDEX idx_city_country ON edm.city (country);

alter table edm.city enable row level security;

create trigger _100_timestamps
  before insert or update on edm.city
  for each row
  execute procedure edm_private.tg__timestamps();

comment on table edm.city is
  E'A city in the application.';

comment on column edm.city.id is
  E'Primary key and id for city.';
comment on column edm.city.name is
  E'Name for city.';
comment on column edm.city.description is
  E'Description for city.';
comment on column edm.city.photo is
  E'Photo for city.';
comment on column edm.city.region is
  E'Region ref for city.';
comment on column edm.city.country is
  E'Region ref for country.';

insert into edm.city (name, description, photo, region, country) values
  ('San Francisco', null, null, 'Bay Area', 'US'),
  ('Berkeley', null, null, 'Bay Area', 'US'),
  ('Sunnyvale', null, null, 'Bay Area', 'US'),
  ('Mountain View', null, null, 'Bay Area', 'US'),
  ('Oakland', null, null, 'Bay Area', 'US'),
  ('Charlotte', null, null, 'Carolina', 'US'),
  ('Black Mountain', null, null, 'Carolina', 'US'),
  ('Asheville', null, null, 'Carolina', 'US'),
  ('Columbia', null, null, 'Carolina', 'US'),
  ('Los Angeles', null, null, 'Los Angeles', 'US'),
  ('Venice', null, null, 'Los Angeles', 'US'),
  ('West Hollywood', null, null, 'Los Angeles', 'US'),
  ('Long Beach', null, null, 'Los Angeles', 'US'),
  ('Huntington Beach', null, null, 'Los Angeles', 'US'),
  ('Newport Beach', null, null, 'Los Angeles', 'US'),
  ('Santa Monica', null, null, 'Los Angeles', 'US'),
  ('Costa Mesa', null, null, 'Los Angeles', 'US'),
  ('Santa Barbara', null, null, 'Los Angeles', 'US'),
  ('Tustin', null, null, 'Los Angeles', 'US'),
  ('Santa Ana', null, null, 'Los Angeles', 'US'),
  ('Irvine', null, null, 'Los Angeles', 'US'),
  ('San Bernardino', null, null, 'Los Angeles', 'US'),
  ('Whittier', null, null, 'Los Angeles', 'US'),
  ('Anaheim', null, null, 'Los Angeles', 'US'),
  ('Pomona', null, null, 'Los Angeles', 'US'),
  ('Inglewood', null, null, 'Los Angeles', 'US'),
  ('San Diego', null, null, 'San Diego', 'US'),
  ('Chula Vista', null, null, 'San Diego', 'US'),
  ('Del Mar', null, null, 'San Diego', 'US'),
  ('Portland', null, null, 'Oregon', 'US'),
  ('Eugene', null, null, 'Oregon', 'US'),
  ('Troutdale', null, null, 'Oregon', 'US'),
  ('Ashland', null, null, 'Oregon', 'US'),
  ('Newberg', null, null, 'Oregon', 'US'),
  ('Ridgefield', null, null, 'Washington', 'US'),
  ('Seattle', null, null, 'Washington', 'US'),
  ('Redmond', null, null, 'Washington', 'US'),
  ('Houston', null, null, 'Texas', 'US'),
  ('Austin', null, null, 'Texas', 'US'),
  ('Leander', null, null, 'Texas', 'US'),
  ('Dallas', null, null, 'Texas', 'US'),
  ('El Paso', null, null, 'Southwest', 'US'),
  ('Las Cruces', null, null, 'Southwest', 'US'),
  ('Vancouver', null, null, 'British Columbia', 'CA'),
  ('Surrey', null, null, 'British Columbia', 'CA'),
  ('Revelstoke', null, null, 'British Columbia', 'CA'),
  ('Victoria', null, null, 'British Columbia', 'CA'),
  ('Nelson', null, null, 'British Columbia', 'CA'),
  ('Whistler', null, null, 'British Columbia', 'CA'),
  ('Sun Peaks', null, null, 'British Columbia', 'CA'),
  ('Fernie', null, null, 'British Columbia', 'CA'),
  ('Kelowna', null, null, 'British Columbia', 'CA'),
  ('Fairmont Hot Springs', null, null, 'British Columbia', 'CA'),
  ('Merritt', null, null, 'British Columbia', 'CA'),
  ('Salmo', null, null, 'British Columbia', 'CA'),
  ('Minneapolis', null, null, 'Twin Cities', 'US'),
  ('St Paul', null, null, 'Twin Cities', 'US'),
  ('Atlanta', null, null, 'Georgia', 'US'),
  ('Decatur', null, null, 'Georgia', 'US'),
  ('Athens', null, null, 'Georgia', 'US'),
  ('Braselton', null, null, 'Georgia', 'US'),
  ('Hampton', null, null, 'Georgia', 'US'),
  ('Detroit', null, null, 'Michigan', 'US'),
  ('Ferndale', null, null, 'Michigan', 'US'),
  ('Pontiac', null, null, 'Michigan', 'US'),
  ('Wyandotte', null, null, 'Michigan', 'US'),
  ('Interlochen', null, null, 'Michigan', 'US'),
  ('Grand Rapids', null, null, 'Michigan', 'US'),
  ('Washington', null, null, 'DC', 'US'),
  ('Baltimore', null, null, 'DC', 'US'),
  ('Columbia', null, null, 'DC', 'US'),
  ('College Park', null, null, 'DC', 'US'),
  ('Silver Spring', null, null, 'DC', 'US'),
  ('Richmond', null, null, 'DC', 'US'),
  ('Sacramento', null, null, 'Sacramento', 'US'),
  ('Auburn', null, null, 'Sacramento', 'US'),
  ('Emigrant Gap', null, null, 'Sacramento', 'US'),
  ('Reno', null, null, 'Nevada', 'US'),
  ('Las Vegas', null, null, 'Nevada', 'US'),
  ('Crystal Bay', null, null, 'Nevada', 'US'),
  ('Milwaukee', null, null, 'Wisconsin', 'US'),
  ('Madison', null, null, 'Wisconsin', 'US'),
  ('Chicago', null, null, 'Chicago', 'US'),
  ('Lisle', null, null, 'Chicago', 'US'),
  ('Lombard', null, null, 'Chicago', 'US'),
  ('Stone Park', null, null, 'Chicago', 'US'),
  ('New York', null, null, 'New York', 'US'),
  ('Brooklyn', null, null, 'New York', 'US'),
  ('Flushing', null, null, 'New York', 'US'),
  ('Paterson', null, null, 'New York', 'US'),
  ('Roselle', null, null, 'New York', 'US'),
  ('Maspeth', null, null, 'New York', 'US'),
  ('Ridgewood', null, null, 'New York', 'US'),
  ('Buffalo', null, null, 'New York', 'US'),
  ('Niagara Falls', null, null, 'New York', 'US'),
  ('Toronto', null, null, 'Ontario', 'CA'),
  ('London', null, null, 'Ontario', 'CA'),
  ('Hamilton', null, null, 'Ontario', 'CA'),
  ('Kitchener', null, null, 'Ontario', 'CA'),
  ('Ottawa', null, null, 'Ontario', 'CA'),
  ('Salt Lake City', null, null, 'Utah', 'US'),
  ('Park City', null, null, 'Utah', 'US'),
  ('Kansas City', null, null, 'Heartland', 'US'),
  ('St. Louis', null, null, 'Heartland', 'US'),
  ('Wichita', null, null, 'Heartland', 'US'),
  ('Tulsa', null, null, 'Heartland', 'US'),
  ('Oklahoma City', null, null, 'Heartland', 'US'),
  ('Iowa City', null, null, 'Heartland', 'US'),
  ('Lincoln', null, null, 'Heartland', 'US'),
  ('St Charles', null, null, 'Heartland', 'US'),
  ('Omaha', null, null, 'Heartland', 'US'),
  ('Columbia', null, null, 'Heartland', 'US'),
  ('Des Moines', null, null, 'Heartland', 'US'),
  ('Lacygne', null, null, 'Heartland', 'US'),
  ('Springfield', null, null, 'Heartland', 'US'),
  ('Lawrence', null, null, 'Heartland', 'US'),
  ('University City', null, null, 'Heartland', 'US'),
  ('Bellevue', null, null, 'Heartland', 'US'),
  ('Orlando', null, null, 'Florida', 'US'),
  ('Miami', null, null, 'Florida', 'US'),
  ('Miami Beach', null, null, 'Florida', 'US'),
  ('Jacksonville', null, null, 'Florida', 'US'),
  ('Clearwater', null, null, 'Florida', 'US'),
  ('St. Petersburg', null, null, 'Florida', 'US'),
  ('Winter Park', null, null, 'Florida', 'US'),
  ('West Palm Beach', null, null, 'Florida', 'US'),
  ('Tampa', null, null, 'Florida', 'US'),
  ('Fort Lauderdale', null, null, 'Florida', 'US'),
  ('Lake Buena Vista', null, null, 'Florida', 'US'),
  ('Gainseville', null, null, 'Florida', 'US'),
  ('Baton Rouge', null, null, 'South', 'US'),
  ('New Orleans', null, null, 'South', 'US'),
  ('Orange Beach', null, null, 'South', 'US'),
  ('Biloxi', null, null, 'South', 'US'),
  ('Tuscaloosa', null, null, 'South', 'US'),
  ('Birmingham', null, null, 'South', 'US'),
  ('Fayetteville', null, null, 'South', 'US'),
  ('Gulf Shores', null, null, 'South', 'US'),
  ('Ozark', null, null, 'South', 'US'),
  ('Montréal', null, null, 'Quebec', 'CA'),
  ('Québec', null, null, 'Quebec', 'CA'),
  ('Sherbrooke', null, null, 'Quebec', 'CA'),
  ('Brossard', null, null, 'Quebec', 'CA'),
  ('Trois-Rivières', null, null, 'Quebec', 'CA'),
  ('Saint-André-Avellin', null, null, 'Quebec', 'CA'),
  ('Knoxville', null, null, 'Tennessee', 'US'),
  ('Memphis', null, null, 'Tennessee', 'US'),
  ('Nashville', null, null, 'Tennessee', 'US'),
  ('Phoenix', null, null, 'Southwest', 'US'),
  ('Tuscon', null, null, 'Southwest', 'US'),
  ('Tempe', null, null, 'Southwest', 'US'),
  ('Scottsdale', null, null, 'Southwest', 'US'),
  ('Mesa', null, null, 'Southwest', 'US'),
  ('Flagstaff', null, null, 'Southwest', 'US'),
  ('Chandler', null, null, 'Southwest', 'US'),
  ('Arcosanti', null, null, 'Southwest', 'US'),
  ('Santa Fe', null, null, 'Southwest', 'US'),
  ('Albuquerque', null, null, 'Southwest', 'US'),
  ('Philadelphia', null, null, 'Pennsylvania', 'US'),
  ('Pittsburgh', null, null, 'Pennsylvania', 'US'),
  ('West Chester', null, null, 'Pennsylvania', 'US'),
  ('Braddock', null, null, 'Pennsylvania', 'US'),
  ('Harrisburg', null, null, 'Pennsylvania', 'US'),
  ('Millvale', null, null, 'Pennsylvania', 'US'),
  ('Lakewood', null, null, 'Pennsylvania', 'US'),
  ('Scranton', null, null, 'Pennsylvania', 'US'),
  ('Artemas', null, null, 'Pennsylvania', 'US'),
  ('Bethelhem', null, null, 'Pennsylvania', 'US'),
  ('University Park', null, null, 'Pennsylvania', 'US'),
  ('Aspen', null, null, 'Rockies', 'US'),
  ('Denver', null, null, 'Rockies', 'US'),
  ('Dillon', null, null, 'Rockies', 'US'),
  ('Fort Collins', null, null, 'Rockies', 'US'),
  ('Boulder', null, null, 'Rockies', 'US'),
  ('Steamboat Springs', null, null, 'Rockies', 'US'),
  ('Avon', null, null, 'Rockies', 'US'),
  ('Winter Park', null, null, 'Rockies', 'US'),
  ('Englewood', null, null, 'Rockies', 'US'),
  ('Durango', null, null, 'Rockies', 'US'),
  ('Colorado Springs', null, null, 'Rockies', 'US'),
  ('Greeley', null, null, 'Rockies', 'US'),
  ('Broomfield', null, null, 'Rockies', 'US'),
  ('Morrison', null, null, 'Rockies', 'US'),
  ('Hesperus', null, null, 'Rockies', 'US'),
  ('Loveland', null, null, 'Rockies', 'US'),
  ('Garden City', null, null, 'Rockies', 'US'),
  ('Mandan', null, null, 'Rockies', 'US'),
  ('Boise', null, null, 'Rockies', 'US'),
  ('Missoula', null, null, 'Rockies', 'US'),
  ('Fargo', null, null, 'Rockies', 'US'),
  ('Billings', null, null, 'Rockies', 'US'),
  ('Bozeman', null, null, 'Rockies', 'US'),
  ('Sioux Falls', null, null, 'Rockies', 'US'),
  ('Carpenter', null, null, 'Rockies', 'US'),
  ('Cheyenne', null, null, 'Rockies', 'US'),
  ('Columbus', null, null, 'Rust Belt', 'US'),
  ('Cleveland', null, null, 'Rust Belt', 'US'),
  ('Lakewood', null, null, 'Rust Belt', 'US'),
  ('Cincinnati', null, null, 'Rust Belt', 'US'),
  ('Athens', null, null, 'Rust Belt', 'US'),
  ('Novelty', null, null, 'Rust Belt', 'US'),
  ('Thornville', null, null, 'Rust Belt', 'US'),
  ('Evansville', null, null, 'Rust Belt', 'US'),
  ('Morgantown', null, null, 'Rust Belt', 'US'),
  ('Indianapolis', null, null, 'Rust Belt', 'US'),
  ('Louisville', null, null, 'Rust Belt', 'US'),
  ('Lexington', null, null, 'Rust Belt', 'US'),
  ('Bloomington', null, null, 'Rust Belt', 'US'),
  ('Newport', null, null, 'Rust Belt', 'US'),
  ('Atlantic City', null, null, 'New Jersey', 'US'),
  ('Neptune City', null, null, 'New Jersey', 'US'),
  ('Calgary', null, null, 'Alberta', 'CA'),
  ('Edmonton', null, null, 'Alberta', 'CA'),
  ('Red Deer', null, null, 'Alberta', 'CA'),
  ('Hartford', null, null, 'Northeast', 'US'),
  ('Uncasville', null, null, 'Northeast', 'US'),
  ('Montville', null, null, 'Northeast', 'US'),
  ('South Burlington', null, null, 'Northeast', 'US'),
  ('Lebanon', null, null, 'Northeast', 'US'),
  ('Ledyard', null, null, 'Northeast', 'US'),
  ('New Haven', null, null, 'Northeast', 'US'),
  ('Portland', null, null, 'Northeast', 'US'),
  ('Pawtucket', null, null, 'Northeast', 'US'),
  ('Sanford', null, null, 'Northeast', 'US'),
  ('Providence', null, null, 'Northeast', 'US'),
  ('Lincoln', null, null, 'Northeast', 'US'),
  ('Bridgeport', null, null, 'Northeast', 'US'),
  ('Concord', null, null, 'Northeast', 'US'),
  ('Boston', null, null, 'Northeast', 'US'),
  ('Cambridge', null, null, 'Northeast', 'US'),
  ('Holyoke', null, null, 'Northeast', 'US'),
  ('Worcester', null, null, 'Northeast', 'US'),
  ('Allston', null, null, 'Northeast', 'US'),
  ('Winnipeg', null, null, 'Manitoba', 'CA'),
  ('Halifax', null, null, 'Nova Scotia', 'CA'),
  ('Saskatoon', null, null, 'Saskatchewan', 'CA'),
  ('Honolulu', null, null, 'Hawaii', 'US'),
  ('Kapolei', null, null, 'Hawaii', 'US'),
  ('Lahaina', null, null, 'Hawaii', 'US'),
  ('Makawao', null, null, 'Hawaii', 'US');
